FROM osrf/ros:melodic-desktop-full


RUN apt-get update &&\
    yes | apt install software-properties-common &&\
    yes "" |add-apt-repository ppa:sdurobotics/ur-rtde &&\
    apt-get update &&\
    apt install librtde librtde-dev &&\
    yes | apt install python3-pip &&\
    pip3 install --upgrade setuptools &&\
    python3 -m pip install -U pip &&\
    pip3 install --user ur_rtde 
    
    # apt-get install terminator

RUN echo "Acquire::GzipIndexes \"false\"; Acquire::CompressionTypes::Order:: \"gz\";" > /etc/apt/apt.conf.d/docker-gzip-indexes
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && TZ=Etc/UTC apt-get install -y --no-install-recommends \
        build-essential \
        sudo \
        less \
        apt-utils \
        tzdata \
        git \
        tmux \
        bash-completion \
        command-not-found \
        software-properties-common \
        curl \
        wget\
        gnupg2 \
        lsb-release \
        keyboard-configuration \
        && \
    apt-get clean 
    # && \
    # rm -rf /var/lib/apt/lists/*

RUN yes |apt install terminator 

USER $USERNAME 
WORKDIR /home/$USERNAME

RUN sudo apt-get update


RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y \
    terminator \
    dbus \
    dbus-x11 \
    gdb \
    rsync \
    nano \
    psmisc \
    inetutils-inetd \
    net-tools \
    inetutils-ping
    
RUN apt-get install -y openssh-server
RUN ssh-keygen -A

RUN apt-get install -y x11-xserver-utils

RUN apt-get update \
    && apt-get install -y \
        libssl-dev \
        libgl1-mesa-dev

RUN yes| apt-get install rviz
WORKDIR /home/$USERNAME
COPY entrypoint.sh .
RUN sudo chmod +x entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
# RUN yes|xhost +local:docker